### ISSUE TITLE
Improve arcadia to accept adding a hyperlink with new tags

### ISSUE THREAD

**Issue by jess192** [roboto84/arcadia_bot#3]
When adding a hyperlink that is already in arcadia, `arcadia_bot` should return the fact that the URL exists, the tag(s) it exists under, and also add the newly given tags

ex:
`/arc add hyperlink https://github.com/jess192 git,jess`

then
`/arc add hyperlink https://github.com/jess192 repo`

Return something like
```sh
github.com/jess192 has already been added with the tags: `git, jess`
adding tag `repo` as well
```

**Comment by roboto84** [comment]
Heads up, I am returning the information that the item is a duplicate, but I am not going to add new tags to the entry.  Message will look like the example below:

`Failed to add duplicate record "https://codeberg.org/kiyui/gnome-shell-night-light-slider-extension/issues/91"
Record already under tags ['night_slider', 'git', 'issue']`

If my message is a bit too robotic, I'd be happy to update it with a simpler and more friendly one.  That said the core work to catch this is done.
